#!/usr/bin/env python3
"""
Email Configuration Setup Script for Aptiva
This script helps you configure email settings for OTP sending.
"""

import os
from pathlib import Path

def setup_email_config():
    """Interactive email configuration setup"""
    print("=" * 60)
    print("Aptiva Email Configuration Setup")
    print("=" * 60)
    print()
    
    # Check if .env exists
    env_path = Path(__file__).parent / '.env'
    env_exists = env_path.exists()
    
    if env_exists:
        print("✅ Found existing .env file")
        response = input("Do you want to update email configuration? (y/n): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    else:
        print("📝 Creating new .env file...")
    
    print()
    print("Email Provider Options:")
    print("1. Gmail (Recommended)")
    print("2. Outlook/Hotmail")
    print("3. Yahoo Mail")
    print("4. Custom SMTP")
    print()
    
    choice = input("Select email provider (1-4): ").strip()
    
    email_config = {}
    
    if choice == '1':
        # Gmail
        email_config['SMTP_SERVER'] = 'smtp.gmail.com'
        email_config['SMTP_PORT'] = '587'
        print()
        print("📧 Gmail Configuration")
        print("=" * 40)
        print("To use Gmail, you need to:")
        print("1. Enable 2-Step Verification in your Google Account")
        print("2. Generate an App Password: https://myaccount.google.com/apppasswords")
        print()
        email_config['EMAIL_FROM'] = input("Enter your Gmail address: ").strip()
        email_config['EMAIL_PASSWORD'] = input("Enter your Gmail App Password (16 characters, no spaces): ").strip().replace(' ', '')
        
    elif choice == '2':
        # Outlook
        email_config['SMTP_SERVER'] = 'smtp-mail.outlook.com'
        email_config['SMTP_PORT'] = '587'
        print()
        print("📧 Outlook/Hotmail Configuration")
        print("=" * 40)
        email_config['EMAIL_FROM'] = input("Enter your Outlook email: ").strip()
        email_config['EMAIL_PASSWORD'] = input("Enter your email password or App Password: ").strip()
        
    elif choice == '3':
        # Yahoo
        email_config['SMTP_SERVER'] = 'smtp.mail.yahoo.com'
        email_config['SMTP_PORT'] = '587'
        print()
        print("📧 Yahoo Mail Configuration")
        print("=" * 40)
        email_config['EMAIL_FROM'] = input("Enter your Yahoo email: ").strip()
        email_config['EMAIL_PASSWORD'] = input("Enter your App Password: ").strip()
        
    elif choice == '4':
        # Custom
        print()
        print("📧 Custom SMTP Configuration")
        print("=" * 40)
        email_config['SMTP_SERVER'] = input("Enter SMTP server (e.g., smtp.example.com): ").strip()
        email_config['SMTP_PORT'] = input("Enter SMTP port (usually 587): ").strip() or '587'
        email_config['EMAIL_FROM'] = input("Enter your email address: ").strip()
        email_config['EMAIL_PASSWORD'] = input("Enter your email password: ").strip()
    else:
        print("Invalid choice. Setup cancelled.")
        return
    
    # Always enable email
    email_config['ENABLE_EMAIL'] = 'true'
    
    # Use the safe update_env.py module to preserve all existing keys
    try:
        from update_env import read_env_file, write_env_file
        
        # Read existing .env if it exists (preserves ALL keys)
        existing_vars = read_env_file(env_path)
        
        # Merge with email config (only update email-related keys)
        for key, value in email_config.items():
            existing_vars[key] = value
        
        # Write .env file safely (preserves all other keys)
        write_env_file(env_path, existing_vars)
        
    except ImportError:
        # Fallback to old method if update_env.py not available
        existing_vars = {}
        if env_exists:
            with open(env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_vars[key.strip()] = value.strip()
        
        # Merge with existing vars (keep non-email vars)
        for key, value in email_config.items():
            existing_vars[key] = value
        
        # Write .env file
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write("# Aptiva Email Configuration\n")
            f.write("# Generated by setup_email.py\n\n")
            
            # Write email config
            f.write("# Email Settings\n")
            f.write(f"ENABLE_EMAIL={existing_vars.get('ENABLE_EMAIL', 'true')}\n")
            f.write(f"EMAIL_FROM={existing_vars.get('EMAIL_FROM', '')}\n")
            f.write(f"EMAIL_PASSWORD={existing_vars.get('EMAIL_PASSWORD', '')}\n")
            f.write(f"SMTP_SERVER={existing_vars.get('SMTP_SERVER', 'smtp.gmail.com')}\n")
            f.write(f"SMTP_PORT={existing_vars.get('SMTP_PORT', '587')}\n")
            f.write("\n")
            
            # Write other existing vars (like GOOGLE_API_KEY)
            other_vars = {k: v for k, v in existing_vars.items() 
                         if k not in ['ENABLE_EMAIL', 'EMAIL_FROM', 'EMAIL_PASSWORD', 'SMTP_SERVER', 'SMTP_PORT']}
            if other_vars:
                f.write("# Other Configuration\n")
                for key, value in other_vars.items():
                    f.write(f"{key}={value}\n")
    
    print()
    print("✅ Email configuration saved to .env file!")
    print()
    print("Next steps:")
    print("1. Restart your backend server")
    print("2. Try signing up with a new email")
    print("3. Check your inbox for the OTP email")
    print()
    print("If email doesn't send, check backend console for error messages.")

if __name__ == "__main__":
    try:
        setup_email_config()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")

